version: "3"

services:

  webapp:
    build: ./webapp
    container_name: webapp
    restart: always
    expose:
      - 8000
    volumes:
      - /run/uwsgi:/run/uwsgi
  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - /run/uwsgi:/run/uwsgi


